"""create jobs table

Revision ID: c09b6eb0608b
Revises: 443f5652452d
Create Date: 2026-06-09 15:16:00.202932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c09b6eb0608b'
down_revision: Union[str, Sequence[str], None] = '443f5652452d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary_from', sa.Float(), nullable=True),
    sa.Column('salary_to', sa.Float(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
